CREATE DATABASE SALES_MANAGEMENT
GO

USE SALES_MANAGEMENT
GO

CREATE TABLE NHANVIEN
(
	MANV VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	TEN VARCHAR(50),
	NGAYSINH SMALLDATETIME,
	GIOITINH VARCHAR(10),
	SDT VARCHAR(20),
	DIACHI VARCHAR(100),
	CONSTRAINT PK_NHANVIEN PRIMARY KEY (MANV)
)
GO

CREATE TABLE QUANLY
(
	MAQL VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	TEN VARCHAR(50),
	NGAYSINH SMALLDATETIME,
	GIOITINH VARCHAR(10),
	SDT VARCHAR(20),
	DIACHI VARCHAR(100),
	CONSTRAINT PK_QUANLY PRIMARY KEY (MAQL),
)
GO

CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(20) NOT NULL,
	TEN VARCHAR(50),
	NGAYSINH SMALLDATETIME,
	GIOITINH VARCHAR(10),
	SDT VARCHAR(20),
	DIACHI VARCHAR(100),
	DIEM INT,
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
)
GO

CREATE TABLE SANPHAM
(
	MASP VARCHAR(20) NOT NULL,
	TEN VARCHAR(100),
	SOLUONG INT,
	DVT VARCHAR(50),
	GIANHAP INT,
	GIABANLE INT,
	HSD SMALLDATETIME,
	NHACUNGCAP VARCHAR(100),
	CONSTRAINT PK_SANPHAM PRIMARY KEY (MASP)
)
GO

CREATE TABLE HOADON
(
	MAHD VARCHAR(20) NOT NULL,
	MANV VARCHAR(20) NOT NULL,
	MAKH VARCHAR(20),
	THOIGIAN SMALLDATETIME,
	STATUS INT NOT NULL DEFAULT 0, -- 0: Chưa thanh toán -- 1: Đã thanh toán
	CONSTRAINT PK_HOADON PRIMARY KEY (MAHD)
)
GO

CREATE TABLE CTHD
(
	MAHD VARCHAR(20) NOT NULL,
	MASP VARCHAR(20) NOT NULL,
	DONGIA INT,
	SOLUONG INT,
	CONSTRAINT PK_CTHD PRIMARY KEY (MAHD, MASP)
)
GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_NHANVIEN_MANV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_HOADON_KHACHHANG_MAKH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
GO

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_HOADON_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
GO

ALTER TABLE CTHD
ADD CONSTRAINT FK_CTHD_SANPHAM_MASP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
GO
